"use client";

//import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";

import { SessionProvider } from 'next-auth/react';

import Header from "@/components/Header";
import Footer from "@/components/Footer";

/* 
 * サーバーサイドコンポーネントなので、一旦コメント。
 * SEO向けにssrやssgで使われている。
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <meta 
          httpEquiv="Content-Security-Policy" 
          content="trusted-types nextjs#bundler;" />
      </head>
      <body className="bg-gray-100 text-gray-900">
        <SessionProvider>
          <Header />
          <main className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">
            {children}
          </main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
